=== IanCBrown/GameInventory/GameInventory/GameItem/Items/item-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for my JSON file format",

  "type": "object",

  "properties": {
    "Id": {
      "type": "integer",
      "description": "ID of the item. For simplicity, it will be an integer starting from 0 corresponding to an Enum."
    },
    "MaxStackableSize": {
      "type": "integer",
      "description": "Max capacity of item in inventory slot.",
      "minimum": 1,
      "maximum": 64
    },
    "Quantity": {
      "type": "integer",
      "description": "Current quantity of item in inventory slot."
    },
    "DisplayName": {
      "type": "string",
      "description": "Display name of the item."
    }
  },
  "required": [ "Id", "MaxStackableSize", "Quantity", "DisplayName"]
}

=== IanCBrown/GameInventory/GameInventory/GameItem/Items/items.json
[
  {
    "Id": 9,
    "MaxStackableSize": 1,
    "Quantity": 1,
    "DisplayName": "Air"
  },
  {
    "Id": 6,
    "MaxStackableSize": 1,
    "Quantity": 1,
    "DisplayName": "Axe"
  },
  {
    "Id": 12,
    "MaxStackableSize": 64,
    "Quantity": 1,
    "DisplayName": "Diamond"
  },
  {
    "Id": 0,
    "MaxStackableSize": 64,
    "Quantity": 1,
    "DisplayName": "Dirt"
  },
  {
    "Id": 8,
    "MaxStackableSize": 16,
    "Quantity": 2,
    "DisplayName": "Ender Pearl"
  },
  {
    "Id": 3,
    "MaxStackableSize": 64,
    "Quantity": 1,
    "DisplayName": "Flower"
  },
  {
    "Id": 4,
    "MaxStackableSize": 1,
    "Quantity": 1,
    "DisplayName": "Pickaxe"
  },
  {
    "Id": 1,
    "MaxStackableSize": 64,
    "Quantity": 1,
    "DisplayName": "Sand"
  },
  {
    "Id": 7,
    "MaxStackableSize": 1,
    "Quantity": 1,
    "DisplayName": "Shovel"
  },
  {
    "Id": 5,
    "MaxStackableSize": 1,
    "Quantity": 1,
    "DisplayName": "Sword"
  },
  {
    "Id": 3,
    "MaxStackableSize": 64,
    "Quantity": 1,
    "DisplayName": "Wood"
  },
  {
    "Id": 10,
    "MaxStackableSize": 64,
    "Quantity": 1,
    "DisplayName": "Wood Plank"
  }
]
